CREATE ROLE hammy_app
  LOGIN
  PASSWORD 'local-hammy-app-password'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION;

GRANT CONNECT, CREATE ON DATABASE hammy TO hammy_app;
GRANT USAGE, CREATE ON SCHEMA public TO hammy_app;

